import { Resend } from 'resend'

const resendApiKey = process.env.RESEND_API_KEY
const resend = resendApiKey ? new Resend(resendApiKey) : null

const EMAIL_FROM = process.env.EMAIL_FROM || 'OceanLK Holdings <noreply@ocean.lk>'
const EMAIL_HR = process.env.EMAIL_HR || 'hr@omc.lk'
const EMAIL_INFO = process.env.EMAIL_INFO || 'info@ocean.lk'

interface SendContactNotificationParams {
  name: string
  email: string
  phone?: string | null
  subject: string
  message: string
}

export async function sendContactNotification(params: SendContactNotificationParams) {
  if (!resend) {
    console.info('[Email Service - Mock Dispatch] New contact message received:', params)
    return { success: true, mock: true }
  }

  try {
    const { data, error } = await resend.emails.send({
      from: EMAIL_FROM,
      to: [EMAIL_INFO],
      replyTo: params.email,
      subject: `[Corporate Inquiry] ${params.subject} - from ${params.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; rounded: 8px;">
          <h2 style="color: #0056b3; border-bottom: 2px solid #0056b3; padding-bottom: 10px;">New Website Contact Inquiry</h2>
          <p><strong>Name:</strong> ${params.name}</p>
          <p><strong>Email:</strong> ${params.email}</p>
          <p><strong>Phone:</strong> ${params.phone || 'Not provided'}</p>
          <p><strong>Subject:</strong> ${params.subject}</p>
          <div style="margin-top: 15px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #0056b3;">
            <p style="white-space: pre-wrap; margin: 0;">${params.message}</p>
          </div>
          <p style="font-size: 11px; color: #888; margin-top: 30px;">This email was automatically generated by OceanLK Web Portal.</p>
        </div>
      `,
    })

    if (error) {
      console.error('Resend email error:', error)
      return { success: false, error: error.message }
    }

    return { success: true, id: data?.id }
  } catch (err: any) {
    console.error('Failed to dispatch contact email:', err)
    return { success: false, error: err.message }
  }
}

interface SendJobApplicationNotificationParams {
  fullName: string
  email: string
  phone: string
  position: string
  experience?: string | null
  cvFilename?: string | null
}

export async function sendJobApplicationNotification(params: SendJobApplicationNotificationParams) {
  if (!resend) {
    console.info('[Email Service - Mock Dispatch] New job application received:', params)
    return { success: true, mock: true }
  }

  try {
    const { data, error } = await resend.emails.send({
      from: EMAIL_FROM,
      to: [EMAIL_HR],
      replyTo: params.email,
      subject: `[Talent Acquisition] Application for ${params.position} - ${params.fullName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; rounded: 8px;">
          <h2 style="color: #0056b3; border-bottom: 2px solid #0056b3; padding-bottom: 10px;">New Job Application Received</h2>
          <p><strong>Candidate:</strong> ${params.fullName}</p>
          <p><strong>Position:</strong> ${params.position}</p>
          <p><strong>Email:</strong> ${params.email}</p>
          <p><strong>Phone:</strong> ${params.phone}</p>
          <p><strong>Experience:</strong> ${params.experience || 'Not specified'}</p>
          <p><strong>Attached CV:</strong> ${params.cvFilename || 'Stored in Supabase Vault'}</p>
          <div style="margin-top: 20px;">
            <a href="${process.env.NEXT_PUBLIC_SITE_URL || 'https://ocean.lk'}/admin/applications" style="background-color: #0056b3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; font-weight: bold;">View in Admin Portal</a>
          </div>
        </div>
      `,
    })

    if (error) {
      console.error('Resend job email error:', error)
      return { success: false, error: error.message }
    }

    return { success: true, id: data?.id }
  } catch (err: any) {
    console.error('Failed to dispatch job application email:', err)
    return { success: false, error: err.message }
  }
}
